name: Test action
on: [push, pull_request, workflow_dispatch]

jobs:
  smoke:
    name: Minimal smoke tests for the action
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Setup Anbox Cloud
      uses: ./
      with:
        channel: 1.24/edge
    - name: Restore cached images
      uses: actions/cache/restore@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
      with:
        path: images
        key: anbox-images-amd64
    - name: Import cached images
      run: |
        amc image add jammy:android13:amd64 ./images/android13.tar.xz
    - name: Tune configuration
      run: |
        amc config set container.security_updates false
    - name: Create Android instance
      id: create-instance
      run: |
        set -x
        id="$(amc launch -r -s adb jammy:android13:amd64)"
        amc wait -c status=running "$id"
        echo "id=$id" >> "$GITHUB_OUTPUT"
    - name: Access Android over ADB
      run: |
        sudo apt install -y adb
        id=${{ steps.create-instance.outputs.id }}
        addr="$(amc show "$id" --format=json | jq -r .network.address)"
        adb connect "$addr":5559
        test "$(adb shell getprop ro.product.model)" = Anbox
